name: espn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  dio: ^4.0.0
  flutter_screenutil: ^5.0.0
  flutter_webview_plugin: ^0.4.0
  cached_network_image: ^3.1.0
  card_swiper: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/logo-espn-light.png
    - assets/images/tabbar-scores-active.png
    - assets/images/tabbar-scores.png
    - assets/images/tabbar-plus-active.png
    - assets/images/tabbar-plus.png
    - assets/images/ESPN_PLUS.png
    - assets/images/default-team-logo.png
    - assets/images/articles-default.png
    - assets/images/articles-header-default.png


